require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 132

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 100
  CountAsOne: ['array', 'hash']

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 15